"""create curinglog table

Revision ID: 8415dda7244c
Revises: 
Create Date: 2026-09-10 19:32:23.345464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '8415dda7244c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curinglog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pi_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('monomer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pi_smiles', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('monomer_smiles', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('environment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uv_dose', sa.Float(), nullable=False),
    sa.Column('logp', sa.Float(), nullable=False),
    sa.Column('pi_concentration', sa.Float(), nullable=False),
    sa.Column('predicted_conversion', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('curinglog')
    # ### end Alembic commands ###
