'''
Database schema for the UV-curing predictor web app.

Uses rx.Model (SQLModel + Pydantic) so the schema is declared as a plain Python class.
Alembic migrations are auto-generated by reflex db make-migrations.
'''

from __future__ import annotations
from datetime import datetime, timezone
import reflex as rx
from pydantic import Field


class CuringLog(rx.Model, table=True):
    '''
    One row per prediction performed via the web app.

    Stores the user's raw input (molecule names, SMILES, parameters) plus
    the model output, so that any prediction can be audited and
    reproduced later.
    '''
    # ---- User input ----
    pi_name: str
    monomer_name: str
    pi_smiles: str
    monomer_smiles: str
    environment: str                # "Solvent" or "Aqueous"
    uv_dose: float                  # mJ/cm²
    logp: float
    pi_concentration: float         # %

    # ---- Model output ----
    predicted_conversion: float     # 0–100

    # ---- Metadata ----
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
